### ISSUE TITLE
example proposal: render as web app

### ISSUE THREAD

**Issue by alisterburt** [tlambert03/microvis#44]
### Description
There is a great example of microvis [displaying something in a jupyter notebook](https://github.com/tlambert03/microvis/blob/main/examples/notebook.ipynb) - it could be cool to see how you might put a remote frame buffer on a webpage. 

I tried to see see if turning the notebook into a web app with [voila](https://voila.readthedocs.io/en/stable/using.html) would work out of the box but ran into some JS issues

```txt
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'RemoteFrameBufferModel' from module 'jupyter_rfb'
Error: Script error for "jupyter_rfb"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (http://localhost:8866/voila/static/require.min.js:1:1067)
    at HTMLScriptElement.onScriptError (http://localhost:8866/voila/static/require.min.js:1:13218)
```

and in the console

```txt
(index):45 Error: Module @jupyter-widgets/base, version ^1.2.0 is not registered, however,         2.0.0 is
    at tn.loadClass (manager.js:158:19)
    at tn.loadClass (manager.js:115:26)
    at tn.loadModelClass (manager-base.js:570:34)
    at tn._make_model (manager-base.js:402:36)
    at tn.new_model (manager-base.js:245:35)
    at manager-base.js:328:32
    at Array.map (<anonymous>)
    at tn._loadFromKernel (manager-base.js:316:40)
    at async tn.build_widgets (manager.js:67:5)
    at async init (main.js?v=07cc494763c3dcb3b604da7aa291ed361b8b163d9cb33c4bc3a66304c18e1dc5bfcf8c6101b6b6426ab36762a01a8568e9f3bf0c7ba6588cd61eab538b95e34a:63:13)
```

**Comment by alisterburt** [comment]
https://github.com/voila-dashboards/voila/issues/1188 did not solve the issue

**Comment by tlambert03** [comment]
yeah, seems cool!
